# BigWarps configuration file version 1.0

# Limit on the number of public warps per player
public_warps_limit: 5

# Limit on the total number of public and private warps per player
total_warps_limit: 15